apiVersion: v1
kind: ResourceQuota
metadata:
  name: monitoring-quota
  namespace: monitoring
spec:
  hard:
    requests.cpu: "3"
    requests.memory: 4Gi
    limits.cpu: "6"
    limits.memory: 8Gi
    pods: "20"
    persistentvolumeclaims: "5"
